### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'ssh'.

### ISSUE THREAD

**Issue by jaydenthorup** [custom-components/sensor.ssh#14]
Logger: homeassistant.loader
Source: loader.py:802
First occurred: March 4, 2021, 8:49:51 PM (2 occurrences)
Last logged: March 4, 2021, 8:49:52 PM

No 'version' key in the manifest file for custom integration 'ssh'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'ssh'

Looks like we need a version key in the manifest file to allow this component to work going forward.

**Comment by jaydenthorup** [comment]
see
https://www.home-assistant.io/blog/2021/03/03/release-20213/#breaking-changes
and the breaking changes


'Custom integrations now require a version key in their manifest file, this also means that all custom integrations now require a manifest file.

If you are using a legacy custom integration like custom_components/awesome.py this now needs to move to custom_components/awesome/__init__.py so you can add custom_components/awesome/manifest.json to it.

For more information about integration, manifests have a look here: https://developers.home-assistant.io/docs/creating_integration_manifest

Custom integrations that do not have this will be blocked from loading if it’s missing a version in the manifest **starting with Home Assistant 2021.6.**

If you see these errors, please report the issue with the author of that custom integration.'

**Comment by mikewren** [comment]
+1 - please and thanks!  👍

**Comment by janjbrand** [comment]
Is it possible to fix this soon? 2021.6 has just been released, so if I upgrade I can't use the component any more.

**Comment by edersong** [comment]
ssh add-on stopped to work when upgraded to 2021.6.0 version today.

**Comment by larserhardsen** [comment]
As a temporary fix, you can add a version attribute to the /custom_components/ssh/manifest.json file

**Comment by edersong** [comment]
@larserhardsen thanks for th information.
Sorry, I'm not skilled in json files.
What text I need to add to the manifest.json file?
Could you show an example?

**Comment by jheizer** [comment]
You can copy my file in the PR from here: https://github.com/jheizer/sensor.ssh/blob/patch-1/custom_components/ssh/manifest.json

**Comment by edersong** [comment]
@jheizer It still not working for me.
Copied the tree files to the /custom_components/ssh/ directory, rebooted the HA and it still failing to load.

**Comment by jheizer** [comment]
What error are you getting in the log?  I just fresh copied it into my environment and restarted and it loaded up fine still.

**Comment by edersong** [comment]
Thanks for the hint!
Found many errors in the manifest.json file.
The corrected one is:

> {
        "domain": "ssh",
        "name": "ssh sensor",
        "documentation": "https://github.com/custom-components/sensor.ssh",
        "requirements": ["pexpect==4.6.0"],
        "dependencies": [],
        "codeowners": ["@jchasey"],
        "version": "0.1.3"
}
