### ISSUE TITLE
scan_interval:

### ISSUE THREAD

**Issue by Norien** [custom-components/sensor.ssh#3]
I would love to control how often this fires for grabbing some local data into docker from other boxes!

**Comment by tiagofreire-pt** [comment]
Me too. :)

**Comment by tiagofreire-pt** [comment]
It seems to be every single minute as far as I can see on my HA instance.

Would be interesting to have this option available for moderating the effort on the sensor and the remote machine. This actually could trigger some IPS or other security routines.

**Comment by Norien** [comment]
I was using a python script to grab data off a secured website, if I hit it too often my IP gets banned for days. I definitely need to limit it to once a day

**Comment by Nixellion** [comment]
I think this option works, I've set it to 5 minutes and it scans every 5 minutes. 
I think scan_interval is in Hass core and it's available for all sensors, at least those that do polling. Component author does not have to add it manually.

**Comment by jchasey** [comment]
Merged pull request adding scan interval
