### ISSUE TITLE
No support for unit_of_measurement

### ISSUE THREAD

**Issue by tiagofreire-pt** [custom-components/sensor.ssh#4]
This is needed for associate units on ssh sensors. Quite useful to be representative.

**Comment by tiagofreire-pt** [comment]
As-well to use the sensor on graphs, otherwise the HA gives the error:

> Entity: sensor.nuc_cpu_temp - Has no Unit of Measurement and therefore can not display a line graph.

**Comment by tiagofreire-pt** [comment]
See pull request: https://github.com/custom-components/sensor.ssh/pull/5

**Comment by jchasey** [comment]
Implemented with PR - thanks!
